@echo off

call 00.dev-info.bat
call 00.key-file-info.bat

set LOCAL_WORK_DIR=.

set OP_INFO_SCPT=r00.op-info
set UPD_AUTH_SCPT=r01.update-auth-key
set RESTORE_AUTH_SCPT=r02.restore-auth-key
set REMOTE_TMP_DIR=/tmp

set REMOTE_SCPTS=%OP_INFO_SCPT% %UPD_AUTH_SCPT% %RESTORE_AUTH_SCPT%
set FILES_SENT_TO_RMT=%AUTH_PUB_KEY_FILE_NAME% %REMOTE_SCPTS%

setlocal enabledelayedexpansion
REM echo REMOTE_SCPTS: %REMOTE_SCPTS%
REM echo FILES_SENT_TO_RMT: %FILES_SENT_TO_RMT%

set FILES_SENT_TO_RMT_WITH_LOCAL_DIR=
for %%i in (%FILES_SENT_TO_RMT%) do (
    set FILES_SENT_TO_RMT_WITH_LOCAL_DIR=!FILES_SENT_TO_RMT_WITH_LOCAL_DIR! %LOCAL_WORK_DIR%\%%i
)

set REMOTE_SCPTS_WITH_RMT_DIR=
for %%i in (%REMOTE_SCPTS%) do (
    set REMOTE_SCPTS_WITH_RMT_DIR=!REMOTE_SCPTS_WITH_RMT_DIR! %REMOTE_TMP_DIR%/%%i
)

endlocal & set REMOTE_SCPTS_WITH_RMT_DIR=%REMOTE_SCPTS_WITH_RMT_DIR% & set FILES_SENT_TO_RMT_WITH_LOCAL_DIR=%FILES_SENT_TO_RMT_WITH_LOCAL_DIR%
